### ISSUE TITLE
卡在”开始尝试登录...“

### ISSUE THREAD

**Issue by Fanchao-Qi** [ulovecode/taobaopanicbuy#1]
感谢大佬分享~
我在试用的时候发现会卡在"开始尝试登录..."，safafi打开后在淘宝主页不动，而并不会弹出登陆界面。
具体好像是卡在这一行：

`WebDriverWait(driver, 100, 0.0001).until(EC.url_matches("https://login.taobao.com"))`

系统是macOS 10.15.4，safari版本是13.1 (15609.1.20.111.8)。

**Comment by ulovecode** [comment]
在谷歌浏览器上，检查二维码元素，然后复制粘贴xpath，替换为之前的。
